### ISSUE TITLE
Partial assertions on deltas

### ISSUE THREAD

**Issue by Druckles** [JDBDT/jdbdt#62]
From the docs it doesn't seem like this is possible but I'd like to be able to use Matchers on data like the following:

    JDBDT.assertInserted(JDBDT.builder(myTable)
            .row(eq(0), eq(1), eq("some value"), anyString(),
                 anyTimestamp(), isGreaterThan(5))

At the moment I'm unable to use any of the `assert` methods because of automatically generated columns that can't easily be predicted like `creation_time`. It would, however, be useful elsewhere for more robust testing like in the Hamcrest-suite.

Is this currently possible? Otherwise I don't know how one can test against the DB directly without fetching the saved data in advance (which kind of defeats the point).

**Comment by edrdo** [comment]
The current API does not support matcher-style assertions. You may use  `TableBuilder.columns()` to specify the columns of interest though (or `QueryBuilder.select`). This will allow you to ignore columns with values that are hard to predict or deemed irrelevant.

**Comment by Druckles** [comment]
Thanks for the reply. Unfortunately the given column can't be `null`, meaning it can't simply be omitted when building the table.

And I haven't figured out how to execute the given `Query` object or obtain the results yet. Is there any more documentation about this? The doc on queries doesn't go past building the object: http://jdbdt.org/DataSources.html.

**Comment by edrdo** [comment]
Perhaps you can use a `Table` object for the purpose of populating the database and then `Query` object(s) for assertions.

`Table` vs `Query` in a nutshell:

- Both can be used with (delta-)assertions - see here  http://jdbdt.org/DBAssertions.html#Snapshots - For that  `Query` objects require an initial `takeSnapshot` call for subsequent assertions (`populate` works for `Table` only, `takeSnapshot` works for both `Table` and `Query`). 
- `Query` objects are of no use otherwise regarding database setup (calls to `populate`, `insert` etc work only with a `Table` object)

I forgot to mention that something along the lines of matcher-like assertions or wildcard column values would be a relevant addition to the library (thanks for the suggestion). I am just not sure if it will be possible to add that support in the next few months.

**Comment by Druckles** [comment]
Thanks. A `Query` was what I wanted; I didn't realise I could use it in my assertions (as a `DataSource`). Now I can ignore fields at will.

But yeah, in the long-term, matcher-like assertions would be great. Being able to do things like, `endsWith(".txt")` or `greaterThan(2)` would provide an extra flexibility.

Thanks for your response!
